name: Feature Request
description: Propose a change or feature to Open Library
labels: ["Type: Feature Request", "Needs: Triage", "Needs: Lead", "Needs: Breakdown"]
body:
  - type: textarea
    attributes:
      label: Proposal
      description: Provide a brief summary of the proposed feature and any details, designs, or screenshots that may be relevant.
      value:

  - type: textarea
    attributes:
      label: Justification
      description: Help us understand, what problem(s) the proposal addresses, what is the predicted impact and how might it be measured, which audiences are served, are there precidents for the feature, and any other context we might consider.
      value: |
      <!-- Problem: What problem does this proposal address and for what audience(s)? -->
      <!-- Impact: What is the predicted impact, how will we measure impact, and what does success look like? -->
      <!-- Research: Are there any precidents or findings from other projects or studies that support this feature? (link or screenshot if possible) -->

  - type: textarea
    attributes:
      label: Breakdown
      description: |
        Instructions and details for completing this feature. Please leave this section blank for leads/maintainers if you are unsure what to enter
      value: |
        #### Requirements Checklist
        <!-- What are the functional pieces or requirements that need to be completed to satisfy this proposal? -->
        - [ ]
        
        #### Related files
        <!-- Files related to the implementation of feature; this is super useful for new contributors who might want to contribute! If you're not sure, leave this blank; a maintainer will add them. -->

        #### Stakeholders
        <!-- @ tag stakeholders of this feature w/ questions or context as necessary -->
        <hr>

        #### Instructions for Contributors
        <!-- Please leave the following reminder section as is to help new contributors and add instructions where necessary -->
        Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

  - type: markdown
    attributes:
      value: |
        **IMPORTANT: Before posting, remove sensitive data, such as passwords, secret keys, session cookies, etc.**

        Thanks for showing interest in adding new features to Open Library! 👍
