name: new_comment_digest
on:
  schedule:  # 08:30 daily
    - cron: '30 8 * * *'
  workflow_dispatch:
    inputs:
      slack_channel:
        description: 'Digest is published to this channel. Include leading `#` symbol in channel name.  Entering an empty string will skip publishing to Slack.'
        type: string
      hours:
        description: 'Search for issues that have new comments within this number of hours.'
        type: number
        required: true
        default: 24
      verbose_mode:
        description: 'Display detailed information about the issues that need responses? (Verbose mode)'
        type: choice
        default: 'No'
        options:
        - 'Yes'
        - 'No'
      label_issues:
        description: 'Add `Needs: Response` labels to issues?'
        type: boolean
        default: false

permissions:
  contents: read
  issues: write

env:
  HOURS: 24
  CHANNEL_ARG: '-s #team-abc-plus'
  VERBOSE_FLAG: ''
  NO_LABELS_FLAG: ''

jobs:
  new_comment_digest:
    # Continue only if this executed on the main repo
    if: ${{ github.repository == 'internetarchive/openlibrary' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install requests
      - name: Override environment variables with inputs when workflow is manually triggered
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          HOURS: ${{ inputs.hours }}
          CHANNEL: ${{ inputs.slack_channel }}
          VERBOSE: ${{ inputs.verbose_mode }}
          USE_LABELS: ${{ inputs.label_issues }}
        run: |
          # Set hours:
          echo "HOURS=$HOURS" >> $GITHUB_ENV
          # Set Slack channel:
          CHANNEL_ARG=""
          if [[ -n $CHANNEL ]]; then
            CHANNEL_ARG="-s \"$CHANNEL\""
          fi
          echo "CHANNEL_ARG=$CHANNEL_ARG" >> $GITHUB_ENV
          # Set verbose flag:
          VERBOSE_FLAG=''
          if [[ $VERBOSE == "Yes" ]]; then
            VERBOSE_FLAG="-v"
          fi
          echo "VERBOSE_FLAG=$VERBOSE_FLAG" >> $GITHUB_ENV
          # Set no_labels flag:
          NO_LABELS_FLAG=""
          if [[ $USE_LABELS == false ]]; then
            NO_LABELS_FLAG="--no-labels"
          fi
          echo "NO_LABELS_FLAG=$NO_LABELS_FLAG" >> $GITHUB_ENV
      - run: scripts/gh_scripts/issue_comment_bot.py ${{ env.HOURS }} -c .github/workflows/config/new_comment_digest.json ${{ env.CHANNEL_ARG }} ${{ env.VERBOSE_FLAG }} ${{ env.NO_LABELS_FLAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
