name: new_comment_digest
on:
  schedule:  # 08:30 daily
    - cron: '30 8 * * *'
  workflow_dispatch:
    inputs:
      slack_channel:
        description: 'Digest is published to this channel. Entering an empty string will prevent publishing.'
        type: string
        default: '#team-abc'
      hours:
        description: 'Search for issues that have new comments within this number of hours'
        required: true
        type: number
        default: 24

permissions:
  contents: read
  issues: write

jobs:
  new_comment_digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install requests
      - run: scripts/gh_scripts/issue_comment_bot.py ${{ inputs.hours }} -c .github/workflows/config/new_comment_digest.json -s "${{ inputs.slack_channel }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
